name = "my_app"
compatibility_date = "2024-08-17"

[vars]
DATABASE_URL= "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYjMyMDU0NDgtZDAxMC00MGNlLTg4MTQtNWEzMGY4Y2M1OTVhIiwidGVuYW50X2lkIjoiYmMxZWJkMTUzNTBjYTVmOWMzZjMxNGEwZTRhM2YyYTY4MzZkZDE2NjIzZWE5ZDY0NGQ3NTg1ZGVhMDA2YmQzNSIsImludGVybmFsX3NlY3JldCI6ImY5ZWIxOGQ3LTBlM2MtNDUzZC1iODY5LTk5ZjMyNmRkY2E5MyJ9.MO_Oxz04Sxka3L_Z3u-7-LfXB0Ia8C7saAy-FXYuJg4"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"